Notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('app.API.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/API/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.authtoken import views

from app.API.resources import NoteList

router = routers.SimpleRouter()
router.register(r'notes', NoteList)

urlpatterns = [
    path('api-token-auth/', views.obtain_auth_token)
]

urlpatterns += router.urls

app/urls.py
from django.urls import path
from app.views import Login, Register, Logout, NoteListView, CreateNote, NoteUpdate, NoteDelete, AboutView


urlpatterns = [
    path('', NoteListView.as_view(), name='base'),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('new-note/', CreateNote.as_view(), name='new_note'),
    path('note-update/<int:pk>/', NoteUpdate.as_view(), name='note_update'),
    path('note-delete/<int:pk>/', NoteDelete.as_view(), name='note_delete'),
    path('about/', AboutView.as_view(), name='about'),

]

app/models.py
from django.contrib.auth.models import User
from django.db import models


class Note(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created']

app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from app.models import Note


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']


class UpdateNoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'text']

app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, TemplateView

from app.forms import RegisterForm, UpdateNoteForm
from app.models import Note


class Login(LoginView):
    success_url = '/'
    template_name = 'login.html'


class Register(CreateView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = '/'


class Logout(LoginRequiredMixin, LogoutView):
    next_page = '/'
    login_url = 'login/'


class NoteListView(LoginRequiredMixin, ListView):
    login_url = 'login/'
    model = Note
    template_name = 'index.html'
    paginate_by = 6


class CreateNote(CreateView):
    model = Note
    fields = ['title', 'text']
    template_name = 'create_note.html'
    success_url = '/'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form=form)


class NoteUpdate(UpdateView):
    model = Note
    form_class = UpdateNoteForm
    template_name = 'update_note.html'
    success_url = '/'


class NoteDelete(DeleteView):
    model = Note
    success_url = '/'


class AboutView(TemplateView):
    template_name = 'about.html'

templates/about.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>About</title>
</head>
<body style="background-image: url('https://cdn.pixabay.com/photo/2016/11/29/01/54/wood-1866667_960_720.jpg');
    background-size: 100%">
    <header>
        <div class="container">
            <a href="{% url 'base' %}"><i class="material-icons cart-icon" style="color: black; font-size: 32px;">arrow_back</i></a>
            <nav>
                <ul>
                    <li><a href="https://github.com/pumaliga"><img src="{% static 'icons/git.png' %}" alt="git"></a></li>
                    <li><a href="mailto:a.kolesnikov040498@gmail.com"><img src="{% static 'icons/mail.png' %}" alt="mail"></a></li>
                    <li><a href="https://www.linkedin.com/in/kolesnikovaa/"><img src="{% static 'icons/link.png' %}" alt="link"></a></li>
                </ul>
            </nav>
  </div>
    </header>
    <div class="main">
        <div class="container">
               <div style="text-align: center">
                   <h1>Welcome!</h1>
                   <h3>This is a site that can be used in place of a paper notebook or text file. You can just open it up and write something down.</h3>
               </div>
        </div>
    </div>
    <footer></footer>

{#    <div id="header">head</div>#}
{#    <div id="main">main</div>#}
{#    <div id="aside">aside</div>#}
{#    <div id="footer">footer</div>#}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>
         {% block title %}
         {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>

templates/create_note.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
	New Note
{% endblock %}

{% block content %}
    <a href="{% url 'base' %}"><i class="material-icons cart-icon" style="color: black; font-size: 48px;">arrow_back</i></a>
    <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light" style="text-align: center">
        <form method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success" style="width: 100%">Create</button>
        </form>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Base page
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    {% if not note_list %}
        <div class="text-center">
            <br>
            <h1 class="text-center">
                Your notebook is empty
            </h1>
            <br>
            <p class="text-center">
                Click <a href="{% url 'new_note' %}">here</a> to go create note
            </p>
        </div>
    {% else %}
        <div class="container">
        <div class="row ">
            {% for notes in note_list %}
            <div class="card border-dark mx-auto my-3 text-center" style="border-radius: 0; height: 30%; width: 30%">
                <div class="card-header" style="border-radius: 0; background-color: #82a9ff">{{ notes.title }}</div>
                <div class="card-body text-dark">
                    <p class="card-text">{{ notes.text }}</p>
                </div>
                <div class="card-footer bg-transparent border-dark">{{ notes.created }}
                    <div class="d-flex justify-content-between">
                        <div>
                            <a href="{% url "note_update" notes.pk %}"><span class="material-icons" style="color: #82a9ff">update</span></a>
                        </div>
                        <div>
                            <form method="post" action="{% url 'note_delete' notes.pk %}">
                                {% csrf_token %}
                                <button style="border-style:none; background: #ffff"><span class="material-icons" style="color: #ff3d58">delete</span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div style="position: relative">
            <div class="pagination" style="justify-content: center;">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
            </span>
        </div>
        </div>
    </div>
    {% endif %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
	Log in
{% endblock %}

{% block content %}

	<div class="container">
		<br>
		<h1 class=" text-center">
			Login or Create a New Account
		</h1>
		<div class="row" style="justify-content: center">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 bg-light">
				<div>
					<br>
					<form method="post">
						{% csrf_token %}
						<p>{{ form | crispy }}</p>
						<button type='submit' class="btn btn-secondary">Login</button>
                        <a href="{% url 'register' %}" class="btn btn-secondary">Create New User</a>
					</form>
					<br>
				</div>
			</div>
		</div>
		<br>
	</div>

{% endblock %}

templates/navbar.html
<div class="navbar-light d-flex justify-content-between"
     style="background-image: url('https://cdn.pixabay.com/photo/2016/02/05/10/13/background-1180666_960_720.jpg');
        background-size: 100%">
    <div class="d-flex">
        <a class="nav-link text-dark" href="{% url 'new_note' %}">
            <span class="material-icons" style="font-size: 48px;">note_add</span></a>
        <a class="nav-link text-dark" href="{% url 'about' %}">
            <span class="material-icons" style="font-size: 48px;">live_help</span></a>
    </div>
    <div>
        <a class="nav-link text-dark " href="{% url 'logout' %}">
            <span class="material-icons" style="font-size: 48px;">logout</span></a>
    </div>
</div>

templates/register.html
{#{% extends 'base.html' %}#}
{##}
{##}
{#{% block content %}#}
{#    <span>Already has account? <a href="{% url 'login' %}">Login</a></span>#}
{#    <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">#}
{#         <form method="post">#}
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            <input type="submit" value="Register">#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}

{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
	Register
{% endblock %}

{% block content %}
    <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
         <form method="post">
             {% csrf_token %}
             {{ form|crispy }}
             <button type='submit' class="btn btn-secondary">Register</button>
             <a href="{% url 'login' %}" class="btn btn-secondary">Login</a>

        </form>
    </div>
{% endblock %}

templates/update_note.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update Note
{% endblock %}

{% block content %}
    <a href="{% url 'base' %}"><i class="material-icons cart-icon" style="color: black; font-size: 48px;">arrow_back</i></a>
    <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light" style="text-align: center">
        <form method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success" style="width: 100%">Update</button>
        </form>
    </div>
{% endblock %}